---
- name: unpack Spark tarball
  unarchive:
    copy=no
    src=/data/spark-{{ spark_version }}-bin-hadoop{{ hadoop_version }}.tar.bz2
    dest={{ spark_install_prefix }}

- name: set owner and group of unpacked Spark files
  file:
    dest={{ spark_install_prefix }}/spark-{{ spark_version }}-bin-hadoop{{ hadoop_version }}
    state=directory
    owner=root
    group={{ spark_group }}
    recurse=yes

- name: link to Spark directory
  file:
    src={{ spark_install_prefix }}/spark-{{ spark_version }}-bin-hadoop{{ hadoop_version }}
    dest={{ spark_install_prefix }}/spark
    state=link
