---
- name: create projects directory
  file:
    path: ~/projects
    state: directory

- name: clone dotfiles repository
  git:
    repo: https://github.com/tjeastman/dotfiles.git
    dest: ~/projects/dotfiles

- name: clone emacs.d repository
  git:
    repo: https://github.com/tjeastman/emacs.d.git
    dest: ~/projects/emacs.d

- name: link to emacs.d
  file:
    src: ~/projects/emacs.d
    dest: ~/.emacs.d
    state: link

- name: create Emacs state directory
  file:
    path: ~/.emacs.d/state
    state: directory

- name: create links
  file:
    src: ~/projects/dotfiles/{{ item }}
    dest: ~/.{{ item }}
    state: link
  with_items:
    - Xdefaults
    - aspell.en.pws
    - avrduderc
    - bash
    - bash_logout
    - bash_profile
    - bashrc
    - ctags
    - gitconfig
    - gitignore.global
    - octaverc
    - profile
    - pylintrc
    - screenrc
    - sqliterc
    - zsh
    - zshrc

- name: install gitconfig.user
  template:
    src: gitconfig.user
    dest: ~/.gitconfig.user

- name: add user to groups
  become: yes
  user:
    name: "{{ username }}"
    state: present
    shell: /bin/zsh
    groups:
      - docker
      - dialout
    append: yes
