---
- name: terminate EC2 instances
  ec2:
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    exact_count: 0
    count_tag:
      class: "{{ class }}"
      created_by: "{{ created_by }}"
      purpose: "{{ purpose }}"
  register: instances
- name: remove public DNS names from local host aliases file
  local_action: lineinfile dest={{ hosts_file }} state=absent line="{{ class }}{{ item.ami_launch_index }} {{ item.public_dns_name }}"
  with_items: instances.tagged_instances
