---
- name: install PlatformIO udev rules file
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules
    dest: /etc/udev/rules.d/99-platformio-udev.rules
    mode: "0644"
  notify:
    - restart udev
