---
- name: install InfluxDB packages
  apt: name={{ item }} update_cache={{ package_cache_update }} state={{ package_state }}
  with_items:
    - influxdb
    - influxdb-client  # FIX put into a different role?
- name: install InfluxDB configuration file
  template: src=influxdb.conf dest=/etc/influxdb
  notify:
    - restart InfluxDB
