---
- name: install st build dependencies (Debian)
  become: yes
  apt:
    name:
      - libfontconfig1-dev
      - libxft-dev
    state: present
  when: ansible_os_family == "Debian"

- name: uninstall system st (Debian)
  become: yes
  apt:
    name:
      - stterm
    state: absent
  when: ansible_os_family == "Debian"
