---
- name: install collectd
  apt: name={{ item }} state=present
  with_items:
    - collectd
    - collectd-utils
- name: install collectd configuration file
  template: src=collectd.conf dest=/etc/collectd
  notify: restart collectd
