---
- name: install collectd packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - collectd
    - collectd-utils

- name: install collectd configuration file
  become: yes
  template:
    src: collectd.conf
    dest: /etc/collectd/
  notify:
    - restart collectd
