---
java_home: /usr/lib/jvm/java-7-openjdk-amd64
hadoop_version: 2.5.2
hadoop_user: root
hadoop_group: hadoop
hadoop_install_prefix: /usr/local
hadoop_config_directory: /usr/local/hadoop/etc/hadoop
hadoop_datanode_file: datanodes
hadoop_name_node: "{{ hostvars[groups['namenode'].0].private_dns_name }}"
hadoop_resource_manager: "{{ hostvars[groups['namenode'].0].private_dns_name }}"
hadoop_data_directory: /hadoop
hadoop_name_directory: /hadoop/name
hadoop_resource_manager_directory: /hadoop/resource
hadoop_dfs_data_directory: /hadoop/dfs
hadoop_dfs_replication: 2
hadoop_dfs_blocksize: 33554432
