---
java_home: /usr/lib/jvm/java-7-openjdk-amd64
hadoop_version: 2.5.1
hadoop_user: debian
hadoop_group: staff
hadoop_install_prefix: /usr/local
hadoop_config_directory: /usr/local/hadoop/etc/hadoop
hadoop_datanode_file: datanodes
hadoop_name_node: hname
hadoop_data_directory: /hadoop
hadoop_name_directory: /hadoop/name
hadoop_resource_manager_directory: /hadoop/resource
hadoop_dfs_data_directory: /hadoop/dfs
hadoop_dfs_replication: 2
hadoop_dfs_blocksize: 33554432
