---
- name: Remove link to HBase directory
  file: dest={{ hbase_install_prefix }}/hbase state=absent
- name: Remove HBase directory
  file: dest={{ hbase_install_prefix }}/hbase-{{ hbase_version }}-hadoop2 state=absent
- name: Remove HBase data directory
  file: dest={{ hbase_data_directory }} state=absent
- name: Remove HBase temporary directory
  file: dest={{ hbase_temporary_directory }} state=absent
- name: Remove zookeeper directory
  file: dest={{ hbase_zookeeper_directory }} state=absent
