---
- name: add Google Linux package signing key
  become: yes
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    id: EB4C1BFD4F042F6DDDCCEC917721F63BD38B4796
    state: present
  when: ansible_os_family == "Debian"
  register: google_package_key

- name: add Google Debian package repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  when: ansible_os_family == "Debian"
  register: google_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - google_package_repository.changed or google_package_key.changed

- name: install Google Chrome
  become: yes
  apt:
    name: google-chrome-stable
    update_cache: no
    state: present
  when: ansible_os_family == "Debian"
