---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    created_by: "{{ username }}"
    purpose: test
    namenodes: 1
    datanodes: 3
    subnet: 192.168.0.0/24
    open_ports:
      - { protocol: tcp, port: 22 }
      - { protocol: tcp, port: 80 }
      - { protocol: tcp, port: 8080 }
      - { protocol: tcp, port: 9090 }
      - { protocol: tcp, port: 8088 }
      - { protocol: tcp, port: 50070 }
      - { protocol: tcp, port: 19888 }
      - { protocol: tcp, port: 9095 }
  roles:
    - role: aws-network
      subnet: "{{ subnet }}"
    - role: aws-node
      count: "{{ namenodes }}"
      class: namenode
    - role: aws-node
      count: "{{ datanodes }}"
      class: datanode
