---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    key_name: primary
    created_by: "{{ username }}"
    purpose: test
    namenodes: 1
    datanodes: 2
    subnet: 192.168.0.0/24
  roles:
    - role: aws-network
      subnet: "{{ subnet }}"
    - role: aws-node
      count: "{{ namenodes }}"
      class: namenode
    - role: aws-node
      count: "{{ datanodes }}"
      class: datanode
