---
- name: add user
  become: yes
  user:
    name: "{{ username }}"
    state: present

- name: set user shell
  become: yes
  user:
    name: "{{ username }}"
    state: present
    shell: "{{ shell }}"
  when: shell is defined

- name: add user to groups
  become: yes
  user:
    name: "{{ username }}"
    state: present
    groups: "{{ groupnames | join(",") }}"
  when: groupnames is defined

- name: add key for user
  become: yes
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', public_key) }}"
    state: present
  when: public_key is defined
