---
- name: add user
  user: name={{ username }} state=present
- name: set user shell
  user: name={{ username }} state=present shell={{ shell }}
  when: shell is defined
- name: print out group names
  debug: var=groupnames
- name: print out group names again
  debug: msg={{ groupnames | join(",") }}
- name: add user to groups
  user: name={{ username }} state=present groups={{ groupnames | join(",") }}
  when: groupnames is defined
- name: add key for user
  authorized_key: user={{ username }} key="{{ lookup('file', public_key) }}" state=present
  when: public_key is defined
