---
- name: install base packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lm-sensors  # FIX run sensors-detect to generate config file

- name: install utility packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - lshw
    - lshw-gtk
    - graphviz
    - diction
    - ffmpegthumbnailer
