---
- name: install TeX packages
  apt: name={{ item }} update_cache={{ package_cache_update }} state={{ package_state }}
  with_items:
    - texlive-latex-base
    - texlive-latex-base-doc
    - texlive-latex-recommended
    - texlive-latex-recommended-doc
