---
- name: install TeX packages
  become: yes
  ansible.builtin.apt:
    name:
      - texlive-extra-utils
      - texlive-fonts-extra
      - texlive-latex-base
      - texlive-latex-base-doc
      - texlive-latex-extra
      - texlive-latex-extra-doc
      - texlive-latex-recommended
      - texlive-latex-recommended-doc
    state: present
