---
- name: install TeX packages
  become: yes
  apt:
    name:
      - texlive-extra-utils
      - texlive-latex-base
      - texlive-latex-base-doc
      - texlive-latex-extra
      - texlive-latex-extra-doc
      - texlive-latex-recommended
      - texlive-latex-recommended-doc
    state: present
  when: ansible_os_family == "Debian"
