---
- name: install TeX packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - texlive-latex-base
    - texlive-latex-base-doc
    - texlive-latex-recommended
    - texlive-latex-recommended-doc
    - texlive-extra-utils
