---
- name: add Bazel package signing key
  become: yes
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    id: 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    state: present
  when: ansible_os_family == "Debian"
  register: bazel_package_key

- name: add Bazel package repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8
    state: present
    filename: bazel
  when: ansible_os_family == "Debian"
  register: bazel_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - bazel_package_repository.changed or bazel_package_key.changed

- name: install Bazel
  become: yes
  apt:
    name: bazel
    state: present
