---
- name: add Bazel package signing key
  become: yes
  apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
    id: 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    state: present
  register: bazel_package_key

- name: add Bazel repository
  become: yes
  copy:
    src: bazel.list
    dest: /etc/apt/sources.list.d/
  register: bazel_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when: bazel_package_repository.changed or bazel_package_key.changed

- name: install Bazel
  become: yes
  apt:
    name: bazel
    update_cache: no
    state: present
