---
- name: add Google Cloud Platform package signing key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  register: google_cloud_package_key

- name: add Google Cloud SDK package repository
  copy:
    src: google-cloud-sdk.list
    dest: /etc/apt/sources.list.d/
  register: google_cloud_package_repository

- name: update APT cache
  apt:
    update_cache: yes
  when: google_cloud_package_repository.changed or google_cloud_package_key.changed

- name: install Google Cloud SDK
  apt:
    name: {{ item }}
    update_cache: no
    state: present
  with_items:
    - google-cloud-sdk
    - google-cloud-sdk-datalab
