---
- name: install Python packages
  apt: name={{ item }} update_cache={{ package_cache_update }} state={{ package_state }}
  with_items:
    - python-dev
    - pyflakes
    - pylint
    - python-flake8
    - python-numpy
    - python-numpy-doc
    - python-scipy
    - python-scipy-doc
    - python-pandas
    - python-tables
    - python-sklearn
    - python-sklearn-doc
    - python-numexpr
    - python-matplotlib
    - python-matplotlib-doc
    - python-virtualenv
    - python-usb
    - python-boto
    - python-gnucash
    - ipython
    - ipython-doc
    - ipython-notebook
