---
- name: install Python packages
  become: yes
  apt:
    name:
      - pipx
      - python-dev-is-python3
      - python-is-python3
      - python3
      - python3-dev
      - python3-doc
      - python3-pip
      - python3-venv
    state: present
  when: ansible_os_family == "Debian"

- name: install Python build packages
  become: yes
  apt:
    name:
      - libbz2-dev
      - liblzma-dev
      - libsqlite3-dev
      - libssl-dev
    state: present
  when: ansible_os_family == "Debian"
