---
- name: install Python packages
  become: yes
  ansible.builtin.apt:
    name:
      - pipx
      - python-dev-is-python3
      - python-is-python3
      - python3
      - python3-dev
      - python3-doc
      - python3-pip
      - python3-venv
    state: present
