---
- name: install Python packages
  become: yes
  apt:
    name:
      - python
      - python-doc
      - python-dev
      - python-pip
      - python-virtualenv
      - python-ipython
      - python-ipython-doc
    state: present
  when: ansible_os_family == "Debian"
