---
- name: install Python packages
  become: yes
  ansible.builtin.apt:
    name:
      - pipx
      - python-dev-is-python3
      - python-is-python3
      - python3
      - python3-dev
      - python3-doc
      - python3-pip
      - python3-venv
    state: present

- name: install Python build packages
  become: yes
  ansible.builtin.apt:
    name:
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - tk-dev
      - zlib1g-dev
    state: present
