---
- name: install Arduino and related packages
  become: yes
  apt:
    name:
      - arduino
      - arduino-core
      - arduino-mk
      - avr-libc
      - avrdude
      - gcc-avr
    state: present
  when: ansible_os_family == "Debian"
