---
- name: install Arduino and related packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - arduino
    - arduino-core
    - arduino-mk
    - avr-libc
    - avrdude
    - gcc-avr
