---
- name: create a new VPC
  ec2_vpc:
    state: present
    region: "{{ region }}"
    cidr_block: "{{ subnet }}"
    internet_gateway: yes
    dns_hostnames: yes
    dns_support: yes
    wait: yes
    resource_tags:
      Name: "{{ created_by }}_{{ purpose }}_vpc"
      created_by: "{{ created_by }}"
      purpose: "{{ purpose }}"
    subnets:
      - cidr: "{{ subnet }}"
        resource_tags:
          Name: "{{ created_by }}_{{ purpose }}_subnet"
          created_by: "{{ created_by }}"
          purpose: "{{ purpose }}"
    route_tables:
      - subnets:
          - "{{ subnet }}"
        routes:
          - dest: 0.0.0.0/0
            gw: igw
  register: vpc
- name: update the default security group for the VPC
  ec2_group:
    state: present
    name: "default"
    description: "default VPC security group"
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc_id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: "{{ subnet }}"
  register: security_group
- name: assign a name to the security group
  ec2_tag: resource={{ security_group.group_id }} region={{ region }}
  args:
    tags:
      Name: "{{ created_by }}_{{ purpose }}_security_group"
      created_by: "{{ created_by }}"
      purpose: "{{ purpose }}"
