---
- name: install packages to support GTK application development
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - glade
    - libgtk-3-0
    - libgtk-3-dev
    - libgtkmm-3.0-dev
