---
- name: add Spotify package signing key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    id: 63CBEEC9006602088F9B19326224F9941A8AA6D1
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg
    state: present
  register: spotify_package_key

- name: add Spotify package repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
  register: spotify_package_repository

- name: update APT cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
  when:
    - spotify_package_repository.changed or spotify_package_key.changed

- name: install Spotify
  become: yes
  ansible.builtin.apt:
    name: spotify-client
    update_cache: no
    state: present
