---
- name: add Spotify package signing key
  become: yes
  apt_key:
    url: https://download.spotify.com/debian/pubkey.gpg
    id: 2EBF997C15BDA244B6EBF5D84773BD5E130D1D45
    state: present
  when: ansible_os_family == "Debian"
  register: spotify_package_key

- name: add Spotify package repository
  become: yes
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
  when: ansible_os_family == "Debian"
  register: spotify_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - spotify_package_repository.changed or spotify_package_key.changed

- name: install Spotify
  become: yes
  apt:
    name: spotify-client
    update_cache: no
    state: present
  when: ansible_os_family == "Debian"
