---
- name: Launch an EC2 instance
  ec2:
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image_id }}"
    region: "{{ region_id }}"
    wait: yes
    count: 1
    group: "{{ group_name }}"
    instance_tags:
      type: "{{ host_type }}"
