---
- name: install UFW
  become: yes
  apt:
    name: ufw
    state: present
  when: ansible_os_family == "Debian"

- name: set policy for outgoing traffic
  become: yes
  ufw:
    direction: outgoing
    policy: allow

- name: set policy for incoming traffic
  become: yes
  ufw:
    direction: incoming
    policy: deny

- name: allow incoming SSH
  become: yes
  ufw:
    name: OpenSSH
    rule: allow

- name: enable UFW
  become: yes
  ufw:
    state: enabled
