---
- name: install Uncomplicated FireWall
  become: yes
  apt:
    name: ufw
    state: present

- name: set policy for outgoing traffic
  become: yes
  ufw:
    direction: outgoing
    policy: allow

- name: set policy for incoming traffic
  become: yes
  ufw:
    direction: incoming
    policy: deny

- name: add firewall rules
  become: yes
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items: "{{ firewall_rules }}"

- name: enable firewall
  become: yes
  ufw:
    state: enabled
