---
- name: install Debian ripgrep package
  become: yes
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.1.1/ripgrep_12.1.1_amd64.deb
    state: present
  when: ansible_distribution == "Debian"

- name: install Ubuntu ripgrep package
  become: yes
  apt:
    name: ripgrep
    state: present
  when: ansible_distribution == "Ubuntu"
