---
- name: install Emacs build packages
  become: yes
  apt:
    name:
      - libgtk-3-dev
      - libXpm
      - libgif-dev
      - libxpm-dev
      - libtiff-dev
      - libgnutls28-dev
      - libxml2-dev
    state: present
  when: ansible_os_family == "Debian"
