---
- name: install compilers and build tools (Debian)
  become: yes
  apt:
    name:
      - clang
      - clang-format
      - clangd
      - clojure
      - cmake
      - g++
      - gcc
      - golang
      - leiningen
      - make
      - nim
    state: present
  when: ansible_os_family == "Debian"

- name: install compilers and build tools (RedHat)
  become: yes
  yum:
    name:
      - gcc
      - make
    state: present
  when: ansible_os_family == "RedHat"
