---
- name: install miscellaneous software development packages
  apt:
    name: {{ item }}
    state: present
  with_items:
    - avrdude
    - gcc-avr
    - avr-libc
    - nasm
    - simple-cdd
    - libusb-dev
    - fritzing
    - fritzing-data
    - arduino
    - arduino-core
    - arduino-mk
    - make
    - gcc
    - g++
    - sdcc
    - clang
    - libclang-dev
    - cmake
    - libssl-dev
    - exuberant-ctags
