---
- name: install base development packages (RedHat)
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - bash-completion
    - bash-completion-extras
    - bind-utils
    - cloud-utils
    - emacs
    - gcc
    - git
    - iperf3
    - make
    - python2-pip
    - rsync
    - screen
    - telnet
    - unzip
    - wget
