---
- name: install Java packages
  become: yes
  apt:
    name:
      - openjdk-11-jre
      - openjdk-11-jdk
      - openjdk-11-doc
      - gradle
    state: present
  when: ansible_os_family == "Debian"
