---
- name: copy HBase
  unarchive:
    copy=yes
    src=download/hbase-{{ hbase_version }}-hadoop2-bin.tar.gz
    dest={{ hbase_install_prefix }}
- name: setup HBase directory
  file:
    dest={{ hbase_install_prefix }}/hbase-{{ hbase_version }}-hadoop2
    state=directory
    owner={{ hbase_user }}
    group={{ hbase_group }}
    recurse=yes
- name: make HBase directory writable
  file:
    dest={{ hbase_install_prefix }}/hbase-{{ hbase_version }}-hadoop2
    state=directory
    mode=775
- name: link to HBase directory
  file:
    src={{ hbase_install_prefix }}/hbase-{{ hbase_version }}-hadoop2
    dest={{ hbase_install_prefix }}/hbase
    state=link
- name: create HBase data directory
  file:
    dest={{ hbase_data_directory }}
    state=directory
    owner={{ hbase_user }}
    group={{ hbase_group }}
    mode=775
- name: create HBase temporary directory
  file:
    dest={{ hbase_temporary_directory }}
    state=directory
    owner={{ hbase_user }}
    group={{ hbase_group }}
    mode=775
- name: create zookeeper directory
  file:
    dest={{ hbase_zookeeper_directory }}
    state=directory
    owner={{ hbase_user }}
    group={{ hbase_group }}
    mode=775
