---
- name: stop YARN node manager
  command: /usr/local/hadoop/sbin/yarn-daemon.sh --config /usr/local/hadoop/etc/hadoop/ stop nodemanager
- name: remove YARN node manager PID file
  file: path=/tmp/yarn-{{ hadoop_user }}-nodemanager.pid state=absent
- name: stop HDFS datanode
  command: /usr/local/hadoop/sbin/hadoop-daemon.sh --config /usr/local/hadoop/etc/hadoop/ --script hdfs stop datanode
- name: remove HDFS datanode PID file
  file: path=/tmp/hadoop-{{ hadoop_user }}-datanode.pid state=absent
