---
- name: delete security group
  ec2_group:
    state: absent
    region: "{{ region }}"
    name: "{{ created_by }}_{{ purpose }}_security_group"
    description: "{{ purpose }} security group ({{ created_by }})"
- name: delete VPC
  ec2_vpc:
    state: absent
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ region }}"
    resource_tags:
      Name: "{{ created_by }}_{{ purpose }}_vpc"
      created_by: "{{ created_by }}"
      purpose: "{{ purpose }}"
