---
- name: install graphite
  apt: name={{ item }} state=latest
  with_items:
    - graphite-carbon
    - graphite-web
- name: install graphite web configuration file
  template: src=local_settings.py dest=/etc/graphite
# FIX need to run this:
# sudo graphite-manage syncdb
- name: install defaults file for Carbon
  copy: src=graphite-carbon dest=/etc/default
- name: install Carbon storage aggregation configuration file
  template: src=storage-aggregation.conf dest=/etc/carbon
- name: install Carbon configuration file
  template: src=carbon.conf dest=/etc/carbon
- name: install Apache
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-wsgi
- name: disable default Apache site
  command: a2dissite 000-default removes=/etc/apache2/sites-enabled/000-default.conf
- name: install Graphite Apache site
  copy: src=apache2-graphite.conf dest=/etc/apache2/sites-available
- name: enable Graphite Apache site
  command: a2ensite apache2-graphite creates=/etc/apache2/sites-enabled/apache2-graphite.conf
