---
- name: add the Etcher package signing key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8756C4F765C9AC3CB6B85D62379CE192D401AB61
    state: present
  when: ansible_os_family == "Debian"
  register: etcher_package_key

- name: add the Etcher package repository
  become: yes
  apt_repository:
    repo: deb https://deb.etcher.io stable etcher
    state: present
    filename: balena-etcher
    mode: 0644
  when: ansible_os_family == "Debian"
  register: etcher_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - etcher_package_repository.changed or etcher_package_key.changed

- name: install Etcher
  become: yes
  apt:
    name: balena-etcher-electron
    update_cache: no
    state: present
  when: ansible_os_family == "Debian"
