---
- name: install miscellaneous software development packages
  apt: name={{ item }} update_cache={{ package_cache_update }} state={{ package_state }}
  with_items:
    - avrdude
    - gcc-avr
    - avr-libc
    - openjdk-7-jdk
    - nasm
    - simple-cdd
    - libusb-dev
    - fritzing
    - fritzing-data
    - arduino
    - arduino-core
    - arduino-mk
    - make
    - gcc
    - g++
    - sdcc
