---
- name: install dnsmasq packages
  become: yes
  ansible.builtin.apt:
    name:
      - dnsmasq
      - dnsmasq-base
    state: present

- name: copy dnsmasq configuration file
  become: yes
  ansible.builtin.template:
    src: local.conf
    dest: /etc/dnsmasq.d/
  notify: restart dnsmasq
