---
- name: add Docker Debian package signing key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  when: ansible_distribution == "Debian"
  register: docker_package_key

- name: add Docker Ubuntu package signing key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  when: ansible_distribution == "Ubuntu"
  register: docker_package_key

- name: add Debian Docker package repository (x86)
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
    filename: docker
    mode: 0644
  when:
    - ansible_distribution == "Debian"
    - ansible_architecture == "x86_64"
  register: docker_package_repository

- name: add Debian Docker package repository (ARM)
  become: yes
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/debian buster stable
    state: present
    filename: docker
    mode: 0644
  when:
    - ansible_distribution == "Debian"
    - ansible_architecture == "armv7l"
  register: docker_package_repository

- name: add Ubuntu Docker package repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: docker
    mode: 0644
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_architecture == "x86_64"
  register: docker_package_repository

- name: update APT cache
  become: yes
  apt:
    update_cache: yes
  when:
    - ansible_os_family == "Debian"
    - docker_package_repository.changed or docker_package_key.changed

- name: install Docker system-level dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_os_family == "Debian"

- name: install Docker and Docker Compose
  become: yes
  apt:
    name:
      - docker-ce
      - docker-compose
    state: present
  when: ansible_os_family == "Debian"
