---
- name: install GNU Octave
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - octave
    - octave-doc
    - octave-info
    - octave-statistics
    - liboctave-dev
