---
- name: install GNU Octave
  become: yes
  apt:
    name:
      - octave
      - octave-doc
      - octave-info
      - octave-statistics
      - liboctave-dev
    state: present
  when: ansible_os_family == "Debian"
