---
- name: install GNU Octave packages
  become: yes
  ansible.builtin.apt:
    name:
      - octave
      - octave-doc
      - octave-info
      - octave-statistics
      - liboctave-dev
    state: present
