---
- name: Update apt cache
  apt: update_cache=yes
- name: Install packages
  apt: name={{ item }} update_cache=no state=latest
  with_items:
    - git
    - git-man
    - emacs
    - zsh
    - screen
    - curl
    - autojump
    - ack-grep
    - unzip
    - python-pip
    - htop
    - wipe
    - minicom
    - texlive-latex-base
    - texlive-latex-base-doc
    - texlive-latex-recommended
    - texlive-latex-recommended-doc
    - python-numpy
    - python-numpy-doc
    - python-scipy
    - python-scipy-doc
    - python-pandas
    - python-tables
    - python-sklearn
    - python-sklearn-doc
    - python-numexpr
    - python-matplotlib
    - python-matplotlib-doc
    - gnuplot
    - gnuplot-doc
