---
- name: install base packages (Debian)
  become: yes
  apt:
    name:
      - aspell
      - bzip2
      - bzip2-doc
      - curl
      - emacs25
      - emacs25-common-non-dfsg  # docs
      - git
      - git-man
      - gnupg2
      - iperf3
      - rsync
      - screen
      - telnet
      - tree
      - unzip
      - wget
      - zsh
      - zsh-doc
    state: present
  when: ansible_os_family == "Debian"

- name: install base packages (RedHat)
  become: yes
  yum:
    name:
    - bash-completion
    - bash-completion-extras
    - emacs
    - git
    - iperf3
    - rsync
    - screen
    - telnet
    - unzip
    - wget
    state: present
  when: ansible_os_family == "RedHat"

- name: install system services (Debian)
  become: yes
  apt:
    name:
      - openssh-server
      - ntp
    state: present
  when: ansible_os_family == "Debian"

- name: install compilers and build tools (Debian)
  become: yes
  apt:
    name:
      - clang
      - cmake
      - g++
      - gcc
      - golang
      - make
    state: present
  when: ansible_os_family == "Debian"

- name: install compilers and build tools (RedHat)
  become: yes
  yum:
    name:
      - gcc
      - make
    state: present
  when: ansible_os_family == "RedHat"
