---
- name: install base packages (Debian)
  become: yes
  apt:
    name:
      - aspell
      - atop
      - autojump
      - bzip2
      - bzip2-doc
      - coreutils
      - cryptsetup
      - curl
      - dmidecode
      - dos2unix
      - emacs-bin-common
      - emacs-common
      - emacs-gtk
      - git
      - git-man
      - glances
      - gnupg2
      - hardinfo
      - htop
      - hwinfo
      - iperf3
      - iptables
      - keychain
      - minicom
      - mysql-client
      - neofetch
      - nmap
      - openconnect
      - openssh-client
      - powertop
      - redis-tools
      - rfkill
      - rsync
      - screen
      - sox
      - sqlite3
      - sshpass
      - strace
      - sysstat
      - telnet
      - tree
      - unzip
      - uuid-runtime
      - vnstat
      - wavemon
      - wget
      - wipe
      - zsh
      - zsh-doc
    state: present
  when: ansible_os_family == "Debian"

- name: install base packages (RedHat)
  become: yes
  yum:
    name:
    - bash-completion
    - bash-completion-extras
    - emacs
    - git
    - iperf3
    - rsync
    - screen
    - telnet
    - unzip
    - wget
    state: present
  when: ansible_os_family == "RedHat"

- name: install system services (Debian)
  become: yes
  apt:
    name:
      - openssh-server
      - ntp
    state: present
  when: ansible_os_family == "Debian"

- name: install compilers and build tools (Debian)
  become: yes
  apt:
    name:
      - clang
      - clojure
      - cmake
      - g++
      - gcc
      - golang
      - make
      - nim
    state: present
  when: ansible_os_family == "Debian"

- name: install compilers and build tools (RedHat)
  become: yes
  yum:
    name:
      - gcc
      - make
    state: present
  when: ansible_os_family == "RedHat"
