---
- name: Update apt cache
  apt: update_cache=yes
- name: Install packages
  apt: name={{ item }} update_cache=no state=latest
  with_items:
    - avrdude
    - gcc-avr
    - avr-libc
    - openjdk-7-jdk
    - nasm
    - simple-cdd
