---
- name: install packages
  apt:
    name: {{ item }}
    state: present
  with_items:
    - git
    - git-man
    - emacs
    - zsh
    - python-pip
    - openssh-client
    - openssh-server
    - lm-sensors  # FIX run sensors-detect to generate config file
    - cryptsetup
    - gnupg2
