---
- name: install packages
  apt: name={{ item }} update_cache={{ package_cache_update }} state={{ package_state }}
  with_items:
    - git
    - git-man
    - emacs
    - zsh
    - python-pip
    - openssh-client
    - openssh-server
    - lm-sensors  # FIX run sensors-detect to generate config file
    - cryptsetup
    - gnupg2
