---
- name: update APT cache
  apt: update_cache=yes
- name: install packages
  apt: name={{ item }} update_cache=no state=latest
  with_items:
    - git
    - git-man
    - emacs
    - zsh
    - python-pip
    - openjdk-7-jdk
