---
- name: update APT cache
  apt: update_cache=yes
- name: install Apache web server
  apt: name=apache2 update_cache=no state=latest
- name: install Ganglia packages
  apt: name={{ item }} update_cache=no state=latest
  with_items:
    - rrdtool
    - gmetad
    - ganglia-webfrontend
- name: configure Ganglia server
  template: src=gmetad.conf dest=/etc/ganglia/
- name: restart Ganglia server
  service: name=gmetad state=restarted
- name: enable Ganglia web frontend
  copy: src=apache.conf dest=/etc/apache2/sites-enabled/
- name: restart Apache web server
  service: name=apache2 state=restarted
