---
- name: update APT cache
  apt: update_cache=yes
- name: install Ganglia packages
  apt: name={{ item }} update_cache=no state=latest
  with_items:
    - rrdtool
    - ganglia-monitor
    - gmetad
    - ganglia-webfrontend
- name: configure Ganglia server
  template: src=gmetad.conf dest=/etc/ganglia/
- name: restart Ganglia server
  service: name=gmetad state=restarted
