---
- name: configure Hadoop cluster nodes
  template: src={{ item }} dest={{ hadoop_config_directory }}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - yarn-site.xml
    - hadoop-env.sh
    - yarn-env.sh
- name: copy Hadoop data node file
  copy: src={{ hadoop_datanode_file }} dest={{ hadoop_config_directory }}
