---
- name: configure Hadoop cluster nodes
  template:
    src={{ item }}
    dest={{ hadoop_config_directory }}
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - yarn-site.xml
    - hadoop-env.sh
    - yarn-env.sh
- name: configure Hadoop cluster nodes to report metrics to Ganglia
  template:
    src=hadoop-metrics2.properties
    dest={{ hadoop_config_directory }}
  when: ganglia_host is defined
- name: copy Hadoop data node file
  template:
    src={{ hadoop_datanode_file }}
    dest={{ hadoop_config_directory }}
