---
- name: install OpenSSH server
  become: yes
  apt:
    name: openssh-server
    state: present

- name: install OpenSSH server configuration
  template:
    src: sshd_config
    dest: /etc/ssh/
    owner: root
    group: root
    mode: 644
  notify:
    - restart ssh server
